use std::sync::Arc;

use rsipstack::dialog::dialog::DialogStateSender;
use rsipstack::dialog::dialog_layer::DialogLayer;
use rsipstack::dialog::invitation::InviteOption;
use rsipstack::Error;
use tracing::{debug, info, warn};

use crate::webrtc::WebRtcSession;

/// Make an outbound call with internally-generated SDP (from rustrtc).
/// Returns (Dialog, WebRtcSession) on success.
pub async fn make_call(
    dialog_layer: Arc<DialogLayer>,
    mut invite_option: InviteOption,
    state_sender: DialogStateSender,
    input_device: Option<String>,
    output_device: Option<String>,
) -> rsipstack::Result<(rsipstack::dialog::dialog::Dialog, WebRtcSession)> {
    let caller = invite_option.caller.to_string();
    let callee = invite_option.callee.to_string();
    let call_id = invite_option.call_id.clone().unwrap_or_default();

    debug!(call_id = %call_id, caller = %caller, callee = %callee, "Preparing outbound call");

    // Create WebRTC session and generate SDP offer
    let (mut session, sdp_offer) = WebRtcSession::new_outbound(
        input_device.as_deref(),
        output_device.as_deref(),
    )
    .await
    .map_err(|e| Error::Error(format!("WebRTC session creation failed: {}", e)))?;

    debug!(call_id = %call_id, sdp_len = sdp_offer.len(), "SDP offer generated by rustrtc");

    // Set the SDP offer
    invite_option.offer = Some(sdp_offer.into_bytes());

    // Send INVITE and wait for response
    info!(call_id = %call_id, "Sending INVITE");
    let (dialog, resp) = dialog_layer.do_invite(invite_option, state_sender).await?;
    let resp = resp.ok_or(Error::Error("No response from remote".to_string()))?;

    if resp.status_code != rsip::StatusCode::OK {
        warn!(call_id = %call_id, callee = %callee, status_code = ?resp.status_code, "Call rejected by remote");
        session.close();
        return Err(Error::Error(format!(
            "Call rejected: {}",
            resp.status_code
        )));
    }

    info!(call_id = %call_id, callee = %callee, "Call answered (200 OK)");

    let sdp_answer = String::from_utf8_lossy(resp.body()).to_string();
    debug!(call_id = %call_id, sdp_answer_len = sdp_answer.len(), "Received SDP answer");

    // Apply SDP answer and start audio
    session
        .apply_answer(&sdp_answer, output_device.as_deref())
        .await
        .map_err(|e| Error::Error(format!("Failed to apply SDP answer: {}", e)))?;

    Ok((
        rsipstack::dialog::dialog::Dialog::ClientInvite(dialog),
        session,
    ))
}
